### PR TITLE
Empty data serialization & Violation-based Error Handling 

### PR DESCRIPTION
**Pull request by chernecov**
**Provide a possibility to serialize empty data**

> Primary data MUST be either:
> - a single resource object, a single resource identifier object, **or null, for requests that target single resources**
> - an array of resource objects, an array of resource identifier objects, **or an empty array ([]), for requests that target resource collections**

**Error handling based on Validation constraints has been added**

### CODE REVIEW

**Comment by RuslanZavacky** [comment]
@chernecov I think you need to also update status code, to be 422 :) Or you've done it already?

**Comment by chernecov** [comment]
@RuslanZavacky Sorry, what status code?

**Comment by RuslanZavacky** [comment]
Response status code. When you return errors, you have to send them with status code = 422 :)

**Comment by chernecov** [comment]
Huh, you mean: "status: the HTTP status code applicable to this problem, expressed as a string value."
Yes, sure, will add. Thanks!

**Comment by RuslanZavacky** [comment]
@chernecov maybe let's merge all your PRs into my branch? I can test it on a production app, to see that everything works as it should? :)

**Comment by chernecov** [comment]
@RuslanZavacky 
Yes, sure, we can merge them to your fork.

I actually moved far away from last PR made here.
No time to wait, so I decided to proceed with my fork->featured branch for now.
And if @koemeet will appear I would prepare pull requests incrementally.

So, actually it is easier for you to take my "featured" branch and continue development there if you are ok with things that I've added/changed/deleted there:

- no hateoas dependency
- errors handling
- violations handle
- additional serializer format "json:api" to not to mess original jms (required for different internal parts of a system)
- empty result serialization
- different pagination
- convenient trait for working from controllers' actions
- added absolute links support
- added exception listener to respond with json:api instead of standard symfony exception page
- moved to yml format for configuration

**Comment by RuslanZavacky** [comment]
I am all up for your changes actually :) The only one thing is about pagination, would be nice somehow not to hardcode CallbackAdapter :)

**Pull request closed without merging**
