### PR TITLE
Refactor Serializer to comply with FosRestBundle changes

### PR DESCRIPTION
**Pull request by renz-ken**
FosRestBundle has changed the way it works with serializers - they now must implement FOS\RestBundle\Serializer\Serializer interface.

### CODE REVIEW

**Comment by koemeet** [comment]
Thanks for contributing @renz-ken! I will look into it as soon as possible. Currently in the middle of a big datacenter migration.

**Comment by renz-ken** [comment]
@steffenbrem thanks - would appreciate you looking into this. We have a whole lot of other improvements that are blocked by this pull request - including deserialization.

**Comment by koemeet** [comment]
This is not backward compatible with `FOSRestBundle` `1.x`. I don't know how many people are using my library, but I first need to release a stable version before I make breaking changes like this one. Otherwise people get a suddenly broken API. I hope you understand that this has to wait till I find time to improve this bundle and release it.

**Comment by renz-ken** [comment]
I understand where you are coming from. It however means that your bundle will not work with the dependencies in their current versions which can stop people from using it and contributing. Would you consider moving the current codebase (compatible with FosRestBundle 1.x) to a separate branch (say, 0.x) and change the FosRestBundle dependency to 2.x in the master branch?
This should only take 5 minutes but will allow this bundle to evolve without affecting legacy users.

**Comment by koemeet** [comment]
I don't want to force users of this bundle to also include FOSRestBundle, with these changes it would not be the case anymore. I will sure look into FOSRestBundle 2 to see what breaks the current serializer from working, didn't have the chance to see what changed in FOSRest.

The only hard dependency should be JMS Serializer and the rest should just be integrations, like I did for `Pagerfanta` etc.

**Comment by RuslanZavacky** [comment]
@steffenbrem I am with @renz-ken here. I was using this bundle as an experiment with one of my projects, with older version. It worked fine. Now I am trying to add it to another project, where FOS Rest Bundle is already added, this bundle is not working unfortunately :(

How I see that, the work that @renz-ken is doing is great and might benefit to all who try/want to use this bundle, but some actions needed, eg. (1) cut current master as some latest versions. (2) we can test and merge @renz-ken change, when its going to be satisfactory, to cut new version as new major release.

@steffenbrem Thank you for your bundle and @renz-ken thank you for your hard work to make it possible to use with latest FOS Rest Bundle.

**Comment by renz-ken** [comment]
We have decided to maintain our own fork at this stage as we require a whole bunch of extra functionality that needs to be shipped asap. I am closing this pull request. Please feel free to merge any of the features from our fork back to this project.

**Pull request closed without merging**
